# Generated by Django 4.1.7 on 2023-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerNombre', models.CharField(max_length=30)),
                ('SegundoNombre', models.CharField(max_length=30)),
                ('PrimerApellido', models.CharField(max_length=30)),
                ('SegundoApellido', models.CharField(max_length=30)),
                ('FechaDeNacimiento', models.DateField()),
                ('GradoCursante', models.CharField(choices=[('1', 'Primer grado'), ('2', 'Segundo grado'), ('3', 'Tercer grado'), ('4', 'Cuarto grado'), ('5', 'Quinto grado'), ('6', 'Sexto grado'), ('7', 'Séptimo grado'), ('8', 'Octavo grado'), ('9', 'Noveno grado'), ('10', 'Décimo grado'), ('11', 'Undécimo grado')], max_length=2)),
                ('FotoDelEstudiante', models.ImageField(upload_to='fotos_estudiantes/')),
            ],
        ),
    ]
